# Site settings
title: Nithin Chandra
description: Custom Rom Developer
baseurl: "mu_blog" # the subpath of your site, e.g. /blog
url: "https://nithin552.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# User Details
username: Nithin Chandra
user_subtitle: Rom Developer
user_description: Hi, I am Nithin,a recent Computer Science graduate. I'm drawn to understanding how things work.I'm Interested in keeping up to date with the latest technologies. I'm a Rom Developer.I like to use github & develop custom roms for various devices.
twitter_username: rkbn552
github_username: Nithin552

sass:
  sass_dir: css
style: compressed


